// Generated by CoffeeScript 1.8.0
(function() {
  var Spy;

  Spy = function(target, method) {
    var result, watchedFunc;
    if (target == null) {
      console.log("target not found");
    }
    if (target[method] == null) {
      console.log("method not found");
    }
    result = {
      count: 0
    };
    watchedFunc = target[method];
    target[method] = function() {
      result.count++;
      return watchedFunc.apply(this, arguments);
    };
    return result;
  };

  module.exports = Spy;

}).call(this);
