// Generated by CoffeeScript 1.8.0
(function() {
  var reduce;

  reduce = function(arr, fn, init) {
    var reducer;
    reducer = function(index, prev) {
      var total;
      if ((arr.length === 0) || (index > arr.length - 1)) {
        return prev;
      }
      total = fn(prev, arr[index], index, arr);
      return reducer(++index, total);
    };
    return reducer(0, init);
  };

  module.exports = reduce;

}).call(this);
