// Generated by CoffeeScript 1.8.0
(function() {
  var checkUsersValid;

  checkUsersValid = function(goodUsers) {
    var submittedUsers;
    return submittedUsers = function() {};
  };

  module.exports = checkUsersValid;

}).call(this);

//# sourceMappingURL=everyarray.js.map
