// Generated by CoffeeScript 1.8.0
(function() {
  var checkUsersValid;

  checkUsersValid = function(goodUsers) {
    return function(submittedUsers) {
      return submittedUsers.every(function(givenuser) {
        return goodUsers.some(function(user) {
          return user.id === givenuser.id;
        });
      });
    };
  };

  module.exports = checkUsersValid;

}).call(this);
