// Generated by CoffeeScript 1.8.0
(function() {
  var duckCount;

  duckCount = function() {
    return Array.prototype.slice.call(arguments).filter(function(duckorNot) {
      return duckorNot.quack != null;
    }).length;
  };

  module.exports = duckCount;

}).call(this);
