// Generated by CoffeeScript 1.8.0
(function() {
  var doubleAll;

  doubleAll = function(numbers) {
    var result;
    return result = numbers.map(function(number) {
      return number * 2;
    });
  };

  module.exports = doubleAll;

}).call(this);

//# sourceMappingURL=map.js.map
