// Generated by CoffeeScript 1.8.0
(function() {
  var repeat;

  repeat = function(operation, num) {
    var i, op, _i;
    for (i = 0 ; i < num; i++) {
      op = operation;
      op();

    }
  };

  module.exports = repeat;

}).call(this);

//# sourceMappingURL=higherorder.js.map
