// Generated by CoffeeScript 1.8.0
(function() {
  var logger, slice;

  slice = Array.prototype.slice;

  logger = function(namespace) {
    return function() {
      return console.log.apply(console, [namespace, slice(arguments).join(" ")]);
    };
  };

  module.exports = logger;

}).call(this);
