// Generated by CoffeeScript 1.8.0
(function() {
  var getShortMessages;

  getShortMessages = function(messages) {
    var res;
    res = [];
    messages.map(function(message) {
      if (message.message.length < 50) {
        return res.push(message.message);
      }
    });
    return res;
  };

  module.exports = getShortMessages;

}).call(this);
