// Generated by CoffeeScript 1.8.0
(function() {
  var getShortMessages;

  getShortMessages = function(messages) {
    var res, result;
    res = [];
    return result = messages.map(function(message) {
      res[0] = res[0] += message.message;
      return console.log(res);
    });
  };

  module.exports = getShortMessages;

}).call(this);

//# sourceMappingURL=arrayfilter.js.map
