// Generated by CoffeeScript 1.8.0
(function() {
  var countwords;

  countwords = function(inputWords) {
    var result;
    return result = inputWords.reduce(function(result, fruit) {
      if (result[fruit] != null) {
        result[fruit]++;
      } else {
        result[fruit] = 1;
      }
      return result;
    }, {});
  };

  module.exports = countwords;

}).call(this);
