// Generated by CoffeeScript 1.8.0
(function() {
  var upperCaser;

  upperCaser = function(input) {
    return input.toUpperCase();
  };

  module.exports = upperCaser;

}).call(this);

//# sourceMappingURL=hello.js.map
