// Generated by CoffeeScript 1.8.0
(function() {
  var arrayMap;

  arrayMap = function(arr, fn) {
    return arr.reduce(function(total, current, index, arr) {
      return total.concat(fn(current, index, arr));
    }, []);
  };

  module.exports = arrayMap;

}).call(this);
